### ISSUE TITLE
Refs not available during child mount in 0.13

### ISSUE THREAD

**Issue by cmwelsh** [cupcake/react-scroll-pagination#7]
In the breaking changes section of the changelog:

https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#breaking-changes

> ref resolution order has changed slightly such that a ref to a component is available immediately after its componentDidMount method is called; this change should be observable only if your component calls a parent component's callback within your componentDidMount, which is an anti-pattern and should be avoided regardless

This means that when the `Page` child component calls the parent component during its mount event, the parent does not have `this.refs.scrollPagination` available. I worked around it by rendering a child-less `ScrollPagination` on the initial render, and then adding the `Page` components later by setting state during the parent `componentDidMount`...

**Comment by jvatic** [comment]
This has currently only been tested with React 0.12, but should be updated in the next month or so for 0.13. Thanks for reporting this!
